AWSTemplateFormatVersion: "2010-09-09"
Description: Bechdel Test Fronts Analyser

Parameters:
  Stage:
    Description: Environment name
    Type: String
    AllowedValues:
    - PROD
    - CODE
  BatchOnePaths:
    Description: Batch one paths
    Type: String
    Default: "/uk,/us,/au,/international,/uk/culture,/us/culture,/au/culture,/uk/business"
  Stack:
    Description: Stack name
    Type: String
    Default: ophan
  App:
    Description: App name
    Type: String
    Default: gu-bechdel-fronts-analyser
  CapiKey:
    Description: Capi key
    Type: String
    Default: xxx
  PGUSER:
    Description: Postgres user
    Type: String
    Default: bechdelmaster
  PGHOST:
    Description: PGHOST
    Type: String
    Default: bechdel-fronts.cii9twl865uw.eu-west-1.rds.amazonaws.com
  PGPASSWORD:
    Description: Pghost
    Type: String
    Default: root1234
  PGDATABASE:
    Description: pg database
    Type: String
    Default: fronts
  PGPORT:
    Description: postgres ports
    Type: Number
    Default: 5432


Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"


  # Event rule that triggers the first lambda every 5 minutes
  BatchOneLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 1 * * ? *)
      Targets:
      - Id: BatchOneLambdaRule
        Arn: !GetAtt [BatchOneLambda, Arn]

  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeBatchOneLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BatchOneLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [BatchOneLambdaRule, Arn]

  # Lambda that querys the flexible API
  BatchOneLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: ophan-dist
        S3Key: !Sub '${Stack}/${Stage}/${App}/${App}.zip'
      FunctionName: !Sub ${App}-BatchOne-${Stage}
      Handler: index.handler
      MemorySize: 512
      Role: !GetAtt [LambdaRole, Arn]
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
          Paths: !Ref BatchOnePaths
          CapiKey: !Ref CapiKey
          PGUSER: !Ref PGUSER
          PGHOST: !Ref PGHOST
          PGPASSWORD: !Ref PGPASSWORD
          PGPORT: !Red PGPORT

  BechdelConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "bechdel-config-bucket"
      Tags:
        -
          Key: "Owner"
          Value: "Jonathan Rankin"

  BechdelBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BechdelConfigBucket
      PolicyDocument:
        Statement:
          -
            Sid: Access-to-Guardian-Office-Only
            Principal: "*"
            Action: "s3:*"
            Effect: Allow
            Resource:
              - Fn::Join: ["", ["arn:aws:s3:::", {Ref: BechdelConfigBucket}]]
              - Fn::Join: ["", ["arn:aws:s3:::", {Ref: BechdelConfigBucket}, "/*"]]
            Condition:
              IpAddress:
                aws:sourceIp: "77.91.248.0/21"
