AWSTemplateFormatVersion: "2010-09-09"
Description: Bechdel Test Fronts Analyser

Parameters:
  Stage:
    Description: Environment name
    Type: String
    AllowedValues:
    - PROD
    - CODE
    Default: PROD
  BatchOnePaths:
    Description: Batch one paths
    Type: String
    Default: "/uk,/us,/au,/international"
  Stack:
    Description: Stack name
    Type: String
    Default: playground
  App:
    Description: App name
    Type: String
    Default: gu-bechdel-fronts-analyser
  CapiKey:
    Description: Capi key
    Type: String
    Default: xxx
  PGUSER:
    Description: Postgres user
    Type: String
    Default: bechdelmaster
  PGHOST:
    Description: PGHOST
    Type: String
    Default: bechdel-store-prod.c0gunnrs6vkk.eu-west-1.rds.amazonaws.com
  PGPASSWORD:
    Description: Pghost
    Type: String
    Default: test1234
  PGDATABASE:
    Description: pg database
    Type: String
    Default: fronts
  PGPORT:
    Description: postgres ports
    Type: Number
    Default: 5432
  GOOGLEAPPLICATIONCREDENTIALS:
    Description: Google GOOGLE_APPLICATION_CREDENTIALS
    Type: String
    Default: test

Mappings:
  Networking:
    VPC:
      CIDR: 10.0.0.0/16
    PublicSubnetOne:
      CIDR: 10.0.1.0/24
    PublicSubnetTwo:
      CIDR: 10.0.2.0/24
    PublicSubnetThree:
      CIDR: 10.0.3.0/24
    PrivateSubnetOne:
      CIDR: 10.0.4.0/24
    PrivateSubnetTwo:
      CIDR: 10.0.5.0/24

Resources:
  BechdelVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - VPC
        - CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
        VpcId: !Ref BechdelVPC
        InternetGatewayId: !Ref InternetGateway
    DependsOn: BechdelVPC
  NATGatewayOne:
    DependsOn:
      - InternetGateway
      - VPCGatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - ElasticIPOne
        - AllocationId
      SubnetId:
        Ref: PublicSubnetOne
  ElasticIPOne:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGatewayTwo:
    DependsOn:
      - InternetGateway
      - VPCGatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - ElasticIPTwo
        - AllocationId
      SubnetId:
        Ref: PublicSubnetTwo
  ElasticIPTwo:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGatewayThree:
    DependsOn:
      - InternetGateway
      - VPCGatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - ElasticIPThree
        - AllocationId
      SubnetId:
        Ref: PublicSubnetThree
  ElasticIPThree:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BechdelVPC
    DependsOn: BechdelVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
    DependsOn:
      VPCGatewayAttachment
  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BechdelVPC
      MapPublicIpOnLaunch: true
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - PublicSubnetOne
        - CIDR
      AvailabilityZone: eu-west-1a
      Tags:
      - Key: Name
        Value: 'Public subnet #1'
  PublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetOne
      RouteTableId:
        Ref: PublicRouteTable
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BechdelVPC
      MapPublicIpOnLaunch: true
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - PublicSubnetTwo
        - CIDR
      AvailabilityZone: eu-west-1b
      Tags:
      - Key: Name
        Value: 'Public subnet #2'
  PublicSubnetTwoRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetTwo
      RouteTableId:
        Ref: PublicRouteTable
  PublicSubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BechdelVPC
      MapPublicIpOnLaunch: true
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - PublicSubnetThree
        - CIDR
      AvailabilityZone: eu-west-1c
      Tags:
      - Key: Name
        Value: 'Public subnet #1'
  PublicSubnetThreeRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnetThree
      RouteTableId:
        Ref: PublicRouteTable
  PrivateRouteTableOne:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: BechdelVPC
  PrivateRouteToInternetOne:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableOne
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATGatewayOne
  PrivateSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnetOne
      RouteTableId:
        Ref: PrivateRouteTableOne
  PrivateSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BechdelVPC
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - PrivateSubnetOne
        - CIDR
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
      Tags:
      - Key: Name
        Value: 'Private subnet #1'
  PrivateRouteTableTwo:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: BechdelVPC
  PrivateRouteToInternetTwo:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableTwo
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATGatewayTwo
  PrivateSubnetTwoRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnetTwo
      RouteTableId:
        Ref: PrivateRouteTableTwo
  PrivateSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: BechdelVPC
      CidrBlock:
        Fn::FindInMap:
        - Networking
        - PrivateSubnetTwo
        - CIDR
      AvailabilityZone:
        Fn::Select:
        - '1'
        - Fn::GetAZs:
            Ref: AWS::Region
      Tags:
      - Key: Name
        Value: 'Private subnet #2'


  BechdelSubnetGroupNew:
    Type: "AWS::RDS::DBSubnetGroup"
    DependsOn:
    - PublicSubnetOne
    - PublicSubnetTwo
    - PublicSubnetThree
    Properties:
      DBSubnetGroupDescription: Subnet group
      DBSubnetGroupName: BechdelSubnetGroupNew
      SubnetIds:
      - Ref: PublicSubnetOne
      - Ref: PublicSubnetTwo
      - Ref: PublicSubnetThree
      Tags:
        - Key: Stack
          Value: !Ref 'Stack'
        - Key: Stage
          Value: !Ref 'Stage'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: ec2
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"


  # Event rule that triggers the first lambda every 5 minutes
  CropOneLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 16 * * ? *)
      Targets:
      - Id: CropOneLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/uk,/us,/au,/international,/uk/culture,/us/culture,/au/culture,/uk/business,/us/business\"}"
  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropOneLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropOneLambdaRule, Arn]

  # Event rule that triggers the first lambda every 5 minutes
  CropTwoLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(10 16 * * ? *)
      Targets:
      - Id: CropTwoLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/au/business,/uk/money,/uk/commentisfree,/us/commentisfree,/au/commentisfree,/uk/environment,/us/environment,/au/environment\"}"
  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropTwoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropTwoLambdaRule, Arn]

  # Event rule that triggers the first lambda every 5 minutes
  CropThreeLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(15 16 * * ? *)
      Targets:
      - Id: CropThreeLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/uk/technology,/us/technology,/au/technology,/uk/sport,/us/sport,/au/sport,/uk/media,/us/media\"}"

  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropThreeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropThreeLambdaRule, Arn]

  # Event rule that triggers the first lambda every 5 minutes
  CropFourLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(30 16 * * ? *)
      Targets:
      - Id: CropFourLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/au/media,/books,/music,/film,/us/film,/au/film,/uk/film\"}"

  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropFourLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropFourLambdaRule, Arn]

  # Event rule that triggers the first lambda every 5 minutes
  CropFiveLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(40 16 * * ? *)
      Targets:
      - Id: CropFiveLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/artanddesign,/stage,/tv-and-radio,/fashion,/lifeandstyle,/politics,/science\"}"

  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropFiveLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropFiveLambdaRule, Arn]

  # Event rule that triggers the first lambda every 5 minutes
  CropSixLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(50 16 * * ? *)
      Targets:
      - Id: CropSixLambdaRule
        Arn: !GetAtt [BechdelLambda, Arn]
        Input:  "{ \"paths\" : \"/football,/travel,/world,/uk-news,/us-news,/australia-news,/observer,/video\"}"

  # Permission to allow the event rule to trigger the flexible querying lambda
  InvokeCropSixLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BechdelLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [CropSixLambdaRule, Arn]

  # Lambda that querys the flexible API
  BechdelLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: playground-dist
        S3Key: !Sub '${Stack}/${Stage}/${App}/${App}.zip'
      FunctionName: !Sub ${App}-BechdelLambda-${Stage}
      Handler: index.handler
      MemorySize: 512
      Role: !GetAtt [LambdaRole, Arn]
      Runtime: nodejs6.10
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - Ref: RDSSecurityGroupClients
        SubnetIds:
          - !Ref PrivateSubnetOne
          - !Ref PrivateSubnetTwo
      Environment:
        Variables:
          Stage: !Ref Stage
          Paths: !Ref BatchOnePaths
          CapiKey: !Ref CapiKey
          PGUSER: !Ref PGUSER
          PGHOST: !Ref PGHOST
          PGPASSWORD: !Ref PGPASSWORD
          PGPORT: !Ref PGPORT
          GOOGLECREDS: !Ref GOOGLEAPPLICATIONCREDENTIALS
          GOOGLE_APPLICATION_CREDENTIALS: '/tmp/creds.json'
    DependsOn:
    - BechdelVPC
    - PublicSubnetOne
    - PublicSubnetTwo
    - PublicSubnetThree

  RDSSecurityGroupClients:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for instances and clients of RDS
      VpcId:
        Ref: BechdelVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  RDSSecurityGroupRules:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group rules
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !Ref 'RDSSecurityGroupClients'
      Tags:
      - Key: Stack
        Value: !Ref 'Stack'
      - Key: Stage
        Value: !Ref 'Stage'
      VpcId:
        Ref: BechdelVPC

  BechdelStore:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      AvailabilityZone: eu-west-1b
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: !Sub bechdel-store-new-${Stage}
      DBName:
        Ref: PGDATABASE
      Port: '5432'
      PubliclyAccessible: 'true'
      StorageType: gp2
      BackupRetentionPeriod: '7'
      MasterUsername:
        Ref: PGUSER
      MasterUserPassword:
        Ref: PGPASSWORD
      PreferredBackupWindow: 03:07-03:37
      PreferredMaintenanceWindow: wed:22:10-wed:22:40
      Engine: postgres
      EngineVersion: 9.5.2
      StorageEncrypted: 'true'
      LicenseModel: postgresql-license
      DBSubnetGroupName:
        Ref: BechdelSubnetGroupNew
      VPCSecurityGroups:
      - !Ref 'RDSSecurityGroupRules'
      Tags:
      - Key: Stack
        Value: !Ref 'Stack'
      - Key: Stage
        Value: !Ref 'Stage'
    DependsOn:
    - BechdelVPC
    - BechdelSubnetGroupNew
    - RDSSecurityGroupRules
    - InternetGateway
    - VPCGatewayAttachment
